config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/hello'

  root to: "static_pages#hello"
  resources :responses, only: [:index, :new, :show, :edit, :update, :destroy]
  get 'responses/create/:forget/:medical/:allowance/:other', to: "responses#create"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/response.rb
class Response < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: [:show, :edit, :update, :destroy]

  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all
    @responses_forget = @responses.where(forget: true).count
    @responses_medical = @responses.where(medical: true).count
    @responses_allowance = @responses.where(allowance: true).count
    @responses_other = @responses.where(other: true).count

  end

  # GET /responses/1
  # GET /responses/1.json
  def show
  end

  # GET /responses/new
  def new
    @response = Response.new
  end

  # GET /responses/1/edit
  def edit
  end

  # POST /responses
  # POST /responses.json
  def create
    @response = Response.new({:forget => params[:forget],:medical => params[:medical],:allowance => params[:allowance],:other => params[:other]})

    respond_to do |format|
      if @response.save
        format.html { redirect_to static_pages_hello_url, notice: 'Response was successfully created.' }
        format.json { render :show, status: :created, location: @response }
      else
        format.html { render :new }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responses/1
  # PATCH/PUT /responses/1.json
  def update
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { render :show, status: :ok, location: @response }
      else
        format.html { render :edit }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response.destroy
    respond_to do |format|
      format.html { redirect_to responses_url, notice: 'Response was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_response
      @response = Response.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def response_params
      params.require(:response).permit(:forget, :medical, :allowance, :other)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def hello
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Emailvert</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/responses/_form.html.erb
<%= form_with(model: response, local: true) do |form| %>
  <% if response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :forget %>
    <%= form.check_box :forget, id: :response_forget %>
  </div>

  <div class="field">
    <%= form.label :medical %>
    <%= form.check_box :medical, id: :response_medical %>
  </div>

  <div class="field">
    <%= form.label :allowance %>
    <%= form.check_box :allowance, id: :response_allowance %>
  </div>

  <div class="field">
    <%= form.label :other %>
    <%= form.check_box :other, id: :response_other %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing Response</h1>

<%= render 'form', response: @response %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Responses</h1>

<table>
  <thead>
    <tr>
      <th>Forget</th>
      <th>Medical</th>
      <th>Allowance</th>
      <th>Other</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.forget %></td>
        <td><%= response.medical %></td>
        <td><%= response.allowance %></td>
        <td><%= response.other %></td>
        <td><%= link_to 'Show', response %></td>
        <td><%= link_to 'Edit', edit_response_path(response) %></td>
        <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <tr>
      <td><%= @responses_forget%></td>
      <td><%=@responses_medical%></td>
      <td><%=@responses_allowance%></td>
      <td><%=@responses_other%></td>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Response', new_response_path %>

app/views/responses/new.html.erb
<h1>New Response</h1>

<%= render 'form', response: @response %>

<%= link_to 'Back', responses_path %>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Forget:</strong>
  <%= @response.forget %>
</p>

<p>
  <strong>Medical:</strong>
  <%= @response.medical %>
</p>

<p>
  <strong>Allowance:</strong>
  <%= @response.allowance %>
</p>

<p>
  <strong>Other:</strong>
  <%= @response.other %>
</p>

<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', responses_path %>

app/views/responses/static_pages.html.erb
<html>

    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <title>Tutsplus Email Newsletter</title>
    <style type="text/css">
        a {
        color: #d80a3e;
        font-size: 16px;
        }

        body,
        #header h1,
        #header h2,
        p {
        margin: 0;
        padding: 0;
        }

        #main {
        border: 1px solid #cfcece;
        }

        img {
        display: block;
        }

        #top-message p,
        #bottom p {
        color: #3f4042;
        font-size: 12px;
        font-family: Arial, Helvetica, sans-serif;
        }

        #header h1 {
        color: #ffffff !important;
        font-family: "Lucida Grande", sans-serif;
        font-size: 24px;
        margin-bottom: 0 !important;
        padding-bottom: 0;
        }

        #header p {
        color: #ffffff !important;
        font-family: "Lucida Grande", "Lucida Sans", "Lucida Sans Unicode", sans-serif;
        font-size: 12px;
        }

        h5 {
        margin: 0 0 0.8em 0;
        }

        h5 {
        font-size: 18px;
        color: #444444 !important;
        font-family: Arial, Helvetica, sans-serif;
        }

        p {
        font-size: 12px;
        color: #444444 !important;
        font-family: "Lucida Grande", "Lucida Sans", "Lucida Sans Unicode", sans-serif;
        line-height: 1.5;
        }
    </style>
    </head>

    <body>


    <table width="100%" cellpadding="0" cellspacing="0" bgcolor="e4e4e4">
        <tr>
        <td>
            <table id="top-message" cellpadding="20" cellspacing="0" width="600" align="center">
            <tr>
                <td></td>
            </tr>
            </table>

            <table id="main" width="600" align="center" cellpadding="0" cellspacing="15" bgcolor="ffffff">
            <tr>
                <td>
                <table id="header" cellpadding="10" cellspacing="0" align="center" bgcolor="8fb3e9">
                    <tr>
                    <td width="570" align="center" bgcolor="#d80a3e">
                        <h1>Justifique sua folha de ponto!</h1>
                    </td>
                    </tr>
                    <tr>
                    <td width="570" align="right" bgcolor="#d80a3e">
                        <p>Janeiro 2019</p>
                    </td>
                    </tr>
                </table>
                </td>
            </tr>

            <tr>
                <td>
                <table id="content-3" cellpadding="0" cellspacing="0" align="center">
                    <tr>
                    <td width="400" valign="top" bgcolor="d0d0d0" style="padding:5px;">
                        <img src="https://www.theworldofchinese.com/wp-content/uploads/2015/05/lateexcuse-master.jpg" width="400" height="230" />
                    </td>
                    </tr>
                </table>
                </td>
            </tr>

            <tr>
                <td>
                <table id="content-4" cellpadding="0" cellspacing="0" align="center">
                    <tr>
                    <td width="400" valign="top" align="center">
                        <h5>Verificamos que no dia X/X/XXX sua folha de ponto do Ahgora estava inconsistente!</h5>
                        <p>Clique no link abaixo para entrar no Ahgora e justificar seus pontos: </p>
                        <a href="https://www.ahgora.com.br/batidas/apuracao">Link do Ahgora</a>
                    </td>
                    </tr>
                </table>
                </td>
            </tr>

            </table>
            <table id="bottom" cellpadding="20" cellspacing="0" width="600" align="center">
            <tr>
                <td align="center"></td>
            </tr>
            </table><!-- top message -->
        </td>
        </tr>
    </table><!-- wrapper -->

    </body>

    </html>

app/views/static_pages/hello.html.erb
<table width="100%" cellpadding="0" cellspacing="0" bgcolor="e4e4e4">
  <tr>
    <td>
      <table id="top-message" cellpadding="20" cellspacing="0" width="600" align="center">
        <tr>
          <td></td>
        </tr>
      </table>

      <table id="main" width="600" align="center" cellpadding="0" cellspacing="15" bgcolor="ffffff">
        <tr>
          <td>
            <table id="header" cellpadding="10" cellspacing="0" align="center" bgcolor="8fb3e9">
              <tr>
                <td height="50" width="570" align="center" bgcolor="#2d753b">
                  <h1>Obrigado por colaborar com este teste!</h1>
                </td>
              </tr>
              <tr>
                <td width="570" align="right" bgcolor="#2d753b">
                  <p>Janeiro 2019</p> 
                  <!-- COLOCAR ESSA PARTE DINÂMICA -->
                </td>
              </tr>
            </table>
          </td>
        </tr>

        <tr>
          <td>
            <table id="content-3" cellpadding="0" cellspacing="0" align="center">
              <tr>
                <td width="400" valign="top" bgcolor="d0d0d0" style="padding:5px;">
                  <img src="https://media2.giphy.com/media/258KoczzDzsbK/giphy.gif" width="400" height="230" />
                </td>
              </tr>
            </table>
          </td>
        </tr>

        <tr>
          <td>
            <table id="content-4" cellpadding="0" cellspacing="0" align="center">
              <tr>
                <td width="400" valign="top" align="center">
                  <h5>Isto era um teste!!! A sua inconsistência no ponto é real e não computamos sua justificativa no ahgora!!</h5>
                  <p class="text-center">Não fique triste, estamos validando esta solução... A partir desta resposta iremos criar uma solução rápida para justificar o ponto e facilitar tanto
                  a sua vida quanto a de seu gestor. Quaisquer feedbacks fique a vontade para nos contactar, estamos
                  no aquário.</p>
                  <a class="link" href="https://www.ahgora.com.br/batidas/apuracao">PS: Não esqueça de realmente justificar a falta no ahgora clicando aqui!!!!!</a>
                </td>
              </tr>
            </table>
          </td>
        </tr>

      </table>
      <table id="bottom" cellpadding="20" cellspacing="0" width="600" align="center">
        <tr>
          <td align="center"></td>
        </tr>
      </table><!-- top message -->
    </td>
  </tr>
</table><!-- wrapper -->